#!/bin/sh
set -eu

for arg in "$@"; do
    case "$arg" in
        /proc/*)
            cd /
            unset LD_PRELOAD ENPASS_FAKE_PID
            exec flatpak-spawn --clear-env --host /bin/cat "$@"
            ;;
    esac
done

exec /usr/bin/cat "$@"
