RUNTIME_ID=org.flatpark.Platform.Zulu21
RUNTIME_SDK_ID=org.flatpark.Sdk.Zulu21
RUNTIME_BRANCH=25.08
RUNTIME_REPOSITORY=https://github.com/flatpark/zulu21-runtime.git
RUNTIME_COMMIT=dd04b8d6b719d1b54fd8a12bd890c8a4a7693920
RUNTIME_MANIFEST=org.flatpark.Sdk.Zulu21.yml
